#!/bin/bash

## https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeo pipefail

commit=$(git rev-parse --short=16 HEAD)

if [ "$PREVIOUS" != "true" ]; then
    echo "Building sci.web $commit"
    rm -rf out
    clojure -A:build
fi

echo "Preparing deploy folder"

# clean, but don't remove entire dist folder, since it's a git worktree
rm -rf dist/js
rm -rf dist/css

mkdir -p dist/js
cp out/main.js "dist/js/main-$commit.js"
mkdir -p dist/css
cp resources/public/css/style.css "dist/css/style-$commit.css"
cp -R resources/public/css/vendor "dist/css/vendor"
cp resources/public/prod.html dist/index.html
sed -i.bak "s/\$COMMIT/$commit/g" dist/index.html
rm "dist/index.html.bak"
