#!/bin/bash

## https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeo pipefail

commit=$(git rev-parse --short=16 HEAD)

if [ "$PREVIOUS" != "true" ]; then
    echo "Building sci.web $commit"
    rm -rf out
    clojure -A:build
fi

echo "Preparing deploy folder"
rm -rf docs
mkdir -p docs/js
cp out/main.js "docs/js/main-$commit.js"
mkdir -p docs/css
cp resources/public/css/style.css "docs/css/style-$commit.css"
cp resources/public/prod.html docs/index.html
sed -i.bak "s/\$COMMIT/$commit/g" docs/index.html
rm "docs/index.html.bak"
